#!/usr/bin/env bash
# AgentHire — Deploy to Vercel
# ============================================================

echo "╔══════════════════════════════════════════════╗"
echo "║   AgentHire — Vercel Deploy Guide            ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "1. Push code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'AgentHire - Initial commit'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/agenthire.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "2. Go to https://vercel.com and import your GitHub repo"
echo ""
echo "3. Add environment variables from .env.local.example:"
echo "   - NEXT_PUBLIC_SUPABASE_URL"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   - SUPABASE_SERVICE_ROLE_KEY"
echo "   - AES_ENCRYPTION_KEY"
echo ""
echo "4. Deploy!"
echo ""
echo "==============================================="
echo "SUPABASE SETUP:"
echo "==============================================="
echo "1. Create project at https://supabase.com"
echo "2. Run schema: copy supabase/schema.sql → SQL Editor"
echo "3. Enable Edge Functions in Supabase dashboard"
echo "4. Deploy edge function:"
echo "   supabase functions deploy job-dispatcher"
echo ""
echo "LOCAL DEV:"
echo "==============================================="
echo "npm install"
echo "npm run dev"
